apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanvi-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tanvi-python-app
  template:
    metadata:
      labels:
        app: tanvi-python-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: master
      containers:
      - name: web
        image: khatanve/tanvi-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
