apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-maven-app
  template:
    metadata:
      labels:
        app: java-maven-app
    spec:
      nodeSelector:
        kubernetes.io/hostname: master
      containers:
      - name: web
        image: khatanve/java-maven-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
