apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanvi-python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tanvi-python-app
  template:
    metadata:
      labels:
        app: tanvi-python-app
    spec:
      containers:
      - name: web
        image: tanvi-python-app:latest
        ports:
        - containerPort: 80

