name: Deploy Python App to Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        export KUBECONFIG=$HOME/.kube/config
        kubectl version --client

    - name: Build Docker image using nerdctl
      run: |
        nerdctl build -t tanvi-python-app:latest .

    - name: Deploy to Kubernetes
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl apply -f manifest/ --validate=false
        kubectl rollout status deployment/tanvi-python-app
