name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
        export KUBECONFIG=$HOME/.kube/config
        kubectl version --client

    - name: Deploy to Kubernetes
      run: |
        export KUBECONFIG=$HOME/.kube/config
        kubectl apply -f manifest/deployment.yaml --validate=false
        kubectl rollout status deployment/tanvi-web
